### ISSUE TITLE
Inconsistent naming of ATAC-only biosamples in cCRE details page

### ISSUE THREAD

**Issue by Jill-Moore** [weng-lab/SCREEN2.0#351]
<img width="1032" alt="Screenshot 2024-06-14 at 4 57 30 PM" src="https://github.com/weng-lab/SCREEN2.0/assets/4357540/808a1d0e-40d6-4b12-b3f1-5dcb9fe21cb4">

Biosamples with ATAC only data are missing commas separating the tissue and sex/age

**Comment by Jill-Moore** [comment]
Also @NishiPhalke can you refresh my memory on how we decided to name the biosamples on this page? Some of them don't look quite right.

**Comment by NishiPhalke** [comment]
@Jill-Moore This logic is used for biosample names:
simpleBiosample = data["simple_biosample_summary"]
tissue = data["biosample_ontology"]["term_name"]
if simpleBiosample == "":
        key = tissue
 else:
        key = tissue + ", " + simpleBiosample

**Comment by Jill-Moore** [comment]
Okay, we should discuss changing for in vitro and organoid samples since the "simpleBiosample" part is not really an accurate description
