### ISSUE TITLE
cCRE numbers should be updated on home page

### ISSUE THREAD

**Issue by Jill-Moore** [weng-lab/SCREEN2.0#352]
> What is SCREEN?
> SCREEN is a web interface for searching and visualizing the Registry of candidate cis-Regulatory Elements (cCREs) derived from ENCODE data. The Registry contains 1,063,878 human cCREs in GRCh38 and 313,838 mouse cCREs in mm10, with homologous cCREs cross-referenced across species. SCREEN presents the data that support biochemical activities of the cCREs and the expression of nearby genes in specific cell and tissue types.

Need to update to 2,348,854 and 926,843

**Comment by jpfisher72** [comment]
Fixed in upcoming PR
