### ISSUE TITLE
Format of human and mouse on download page

### ISSUE THREAD

**Issue by Jill-Moore** [weng-lab/SCREEN2.0#353]
http://screen-beta.wenglab.org/downloads?tab=1

Can the human and mouse sections go side by side?

<img width="1351" alt="Screenshot 2024-06-14 at 5 01 52 PM" src="https://github.com/weng-lab/SCREEN2.0/assets/4357540/68fbf259-1741-4c95-86d8-34b91448b38a">

**Comment by jpfisher72** [comment]
fixed in upcoming PR
