### ISSUE TITLE
Gene Expression App

### ISSUE THREAD

**Issue by Jill-Moore** [weng-lab/SCREEN2.0#367]
- [x] Change default scale to Linear TPM
- [x] Change default View by to Experiment then Tissue then Tissue Max
- [x] #387
- [x] Make it so that it is obvious that links to encode are external (maybe show icon?)
- [x] Is it possible to have a toggle of Show all Biosamples vs. Show Biosamples w/ TPM > 0? That way a user can comparing two genes more easily

**Comment by NishiPhalke** [comment]
- [ ] Redirect GeneCards Link to new tab rather than opening in same window
- [ ] Open ENCODE experiment in new tab on clicking gene exp individual bar
