### ISSUE TITLE
FDR for STARR-seq table

### ISSUE THREAD

**Issue by Jill-Moore** [weng-lab/SCREEN2.0#509]
https://screen-umass.vercel.app/search?assembly=GRCh38&chromosome=chr19&start=12883901&end=12883901&snpid=rs2280742&snpDistance=0&dnase_s=-10&dnase_e=11&h3k4me3_s=-10&h3k4me3_e=11&h3k27ac_s=-10&h3k27ac_e=11&ctcf_s=-10&ctcf_e=11&atac_s=-10&atac_e=11&CA=t&CA_CTCF=t&CA_H3K4me3=t&CA_TF=t&dELS=t&pELS=t&PLS=t&TF=t&prim_s=-2&prim_e=2&mamm_s=-4&mamm_e=8&vert_s=-3&vert_e=8&linkedGeneName=&CTCFChIAPET=t_&RNAPIIChIAPET=t_&HiC=t_&CRISPRiFlowFISH=t_&eQTLs=t_&accessions=EH38E3291349&page=2

<img width="1012" alt="Screenshot 2024-12-11 at 6 24 55 AM" src="https://github.com/user-attachments/assets/b00067a1-aef4-46dd-b38f-bd0c25d8a251">

Possibly due to N.A. value? 

FDR should always be numerically higher than p-value

**Comment by jpfisher72** [comment]
@NishiPhalke Can you look into this? P-value and FDR of 0 is being returned from backend 

```
query capraFccDoubleQuery($accession: [String]!) {
  capraFccDoubleQuery(accession: $accession) {
    rdhs_p1
    rdhs_p2
    log2fc
    fdr
    dna_rep1
    rna_rep1
    rna_rep2
    rna_rep3
    pvalue
    experiment
  }
}
```

```
{
  "accession": "EH38E3291349"
}
```

**Comment by NishiPhalke** [comment]
> https://screen-umass.vercel.app/search?assembly=GRCh38&chromosome=chr19&start=12883901&end=12883901&snpid=rs2280742&snpDistance=0&dnase_s=-10&dnase_e=11&h3k4me3_s=-10&h3k4me3_e=11&h3k27ac_s=-10&h3k27ac_e=11&ctcf_s=-10&ctcf_e=11&atac_s=-10&atac_e=11&CA=t&CA_CTCF=t&CA_H3K4me3=t&CA_TF=t&dELS=t&pELS=t&PLS=t&TF=t&prim_s=-2&prim_e=2&mamm_s=-4&mamm_e=8&vert_s=-3&vert_e=8&linkedGeneName=&CTCFChIAPET=t_&RNAPIIChIAPET=t_&HiC=t_&CRISPRiFlowFISH=t_&eQTLs=t_&accessions=EH38E3291349&page=2
> 
> <img alt="Screenshot 2024-12-11 at 6 24 55 AM" width="1012" src="https://private-user-images.githubusercontent.com/4357540/394718814-b00067a1-aef4-46dd-b38f-bd0c25d8a251.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MjgwMzYsIm5iZiI6MTczMzkyNzczNiwicGF0aCI6Ii80MzU3NTQwLzM5NDcxODgxNC1iMDAwNjdhMS1hZWY0LTQ2ZGQtYjM4Zi1iZDBjMjVkOGEyNTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTFUMTQzNTM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTNjOWJlMDk3NTgxNWQxNWI1NzEzNTkwYmIxZmJiMWI2MTZiN2MxMGYxNWEzYjgzMmRmNjZjZTg3M2ZkMWZlMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.lkiFdiJymo_ZUrS7-A4vUnPkEyWwdzByp8QUpr2Lolo">
> Possibly due to N.A. value?
> 
> FDR should always be numerically higher than p-value

It is due to NA values. Shall we just show NA in table instead of 0 ?
